apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nx1vh67ee-go 
  janus-idp.io/tekton: nx1vh67ee-go
  backstage.io/kubernetes-id: nx1vh67ee-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nx1vh67ee-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml