apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nx1vh67ee-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nx1vh67ee-go 
  name: nx1vh67ee-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nx1vh67ee-go 
